const recommendations = {
  Happy: {
    quotes: [
      "Let your laughter light up the day :3",
      "Happiness is the sunshine you carry inside.",
      "Dance with the breeze, sing with the trees.",
      "Every moment is a reason to smile.(just dont overdo it or u might end up in pysch ward)",
      "Let your heart skip with delight.(do it in limits or u might end up getting heartattack)",
      "Celebrate the little victories.(HELL YEAH)",
      "Share your smile, it’s contagious.",
      "Life sparkles when you do.",
      "Let happiness be your favorite habit.(impossible)",
      "Bright days are made by bright minds.",
      "Chase dreams with a full heart <3.",
      "Good vibes are your superpower.",
      "Choose joy, again and again.",
      "Let your spirit soar above the clouds.(to the space)",
      "which soul are u planning on torturing today?",
      "Its a PERFECT day to have chocolate milk.",
      "Your mood is as it should be :3",
      "you should take out wuxian for a walk",
      "perfect mood to be having carrots"
    ],
    songs: [
      { title: "MIC Drop – BTS", cover: "./coverimages/Bts1.png", link: "https://open.spotify.com/track/01380RE6UfsPSdiUIwrCoH?si=a514193e414d4b3b" },
      { title: "IDOL – BTS", cover: "./coverimages/Bts1.png", link: "https://open.spotify.com/track/1e8J3XClxZbFmvIHLI8CE4?si=0d612cf5cb5747a0" },
      { title: "Blue Hour – TXT", cover: "./coverimages/txt1.png", link: "https://open.spotify.com/track/3ObPkJQAgjAhTwYvDhPrAW?si=7a972b31af234a55" },
      { title: "No Tears Left to Cry – Ariana Grande", cover: "./coverimages/ag1.png", link: "https://open.spotify.com/track/2qT1uLXPVPzGgFOx4jtEuo?si=9c581e1aed07491b" },
      { title: "Interlude – Agust D", cover: "./coverimages/agustd1.png", link: "https://open.spotify.com/track/56tf3cHQkwmvoplotk5QXd?si=7d5f3a6834da421c" },
      { title: "Trivia: Love – BTS", cover: "./coverimages/Bts1.png", link: "https://open.spotify.com/track/6bSwpQYEguyMlkCoWiBt3Y?si=62a355b832974538" },
      { title: "Love Maze – BTS", cover: "./coverimages/Bts2.png", link: "https://open.spotify.com/track/4ROdFnoZNn2RTmwct0cVpx?si=14ef636063754f62" },
      { title: "Euphoria – BTS", cover: "./coverimages/Bts1.png", link: "https://open.spotify.com/track/5YMXGBD6vcYP7IolemyLtK?si=349f8d53ecfd4adc" },
      { title: "Mikrokosmos – BTS", cover: "./coverimages/Bts3.png", link: "https://open.spotify.com/track/0jSccBRnhNU4KtACMQPvco?si=85a93bb201af463b" },
      { title: "Loser=Lover – TXT", cover: "./coverimages/txt2.png", link: "https://open.spotify.com/track/21aOLk12MksET8AsbU0SI6?si=9eae185b75024e40" },
      { title: "Pink Pony Club – Chappell Roan", cover: "./coverimages/cr1.png", link: "https://open.spotify.com/track/1k2pQc5i348DCHwbn5KTdc?si=12a24c5045d343e6" },
      { title: "Girls Just Want to Have Fun – Cyndi Lauper", cover: "./coverimages/cl1.png", link: "https://open.spotify.com/track/4y1LsJpmMti1PfRQV9AWWe?si=8000327caef545e0" },
      { title: "Bubblegum Bitch – MARINA", cover: "./coverimages/marina1.png", link: "https://open.spotify.com/track/6IbnUaczZBT34DhaD6S18F?si=dfb6285b032f4810" },
      { title: "Applause – Lady Gaga", cover: "./coverimages/lg1.png", link: "https://open.spotify.com/track/5ka2ajep9OAvU5Sgduhiex?si=493940c1924141b4" },
      { title: "How to Be a Heartbreaker – MARINA", cover: "./coverimages/marina1.png", link: "https://open.spotify.com/track/2sEk5R8ErGIFxbZ7rX6S2S?si=9c425b4f63254be9" },
      { title: "Naughty – Red Velvet", cover: "./coverimages/rv1.png", link: "https://open.spotify.com/track/0P8lbWigAHXPKxUG60xh79?si=a659692de2db4d26" },
      { title: "Looking at Me – Sabrina Carpenter", cover: "./coverimages/sb1.png", link: "https://open.spotify.com/track/59tskctgqUmjCWAwhzYAFm?si=01d27dd6570243dc" },
      { title: "Sweet Tooth – Scott Helman", cover: "./coverimages/sh1.png", link: "https://open.spotify.com/track/2qROUDWN1RCJoyiVSr6ifm?si=2e4a734c991d4c76" },
      { title: "Dream Song – Lala Lala", cover: "./coverimages/lala1.png", link: "https://open.spotify.com/track/0jTKmPYBGiEZsQtRNlWM1L?si=de2274f6455d4dbc" },
      { title: "Fairytale – Alexander Rybak", cover: "./coverimages/ar1.png", link: "https://open.spotify.com/track/3MnAsEBBsEj86d03RgO4EM?si=c9acdff0df2944cc" }
    ],
    movies: [
      { title: "The Intouchables", genre: "Comedy/Drama", link: "https://myflixerz.to/movie/the-intouchables-19408" },
      { title: "Amélie", genre: "Romantic Comedy", link: "https://myflixerz.to/movie/amelie-19251" },
      { title: "Singin’ in the Rain", genre: "Musical/Comedy", link: "https://myflixerz.to/movie/singin-in-the-rain-17646" },
      { title: "Paddington 2", genre: "Family/Comedy", link: "https://myflixerz.to/movie/paddington-2-17570" },
      { title: "Up", genre: "Animation/Adventure", link: "https://myflixerz.to/movie/up-19453" },
      { title: "Ferris Bueller’s Day Off", genre: "Teen/Comedy", link: "https://myflixerz.to/movie/ferris-buellers-day-off-18475" },
      { title: "Little Miss Sunshine", genre: "Comedy/Drama", link: "https://myflixerz.to/movie/little-miss-sunshine-13953" },
      { title: "The Grand Budapest Hotel", genre: "Comedy/Adventure", link: "https://myflixerz.to/movie/the-grand-budapest-hotel-19149" },
      { title: "School of Rock", genre: "Comedy/Music", link: "https://myflixerz.to/movie/school-of-rock-17781" },
      { title: "Julie & Julia", genre: "Comedy/Biography", link: "https://myflixerz.to/movie/julie-and-julia-17226" },
      { title: "The Princess Bride", genre: "Fantasy/Adventure/Comedy", link: "https://myflixerz.to/movie/the-princess-bride-17632" },
      { title: "Chef", genre: "Comedy/Drama", link: "https://myflixerz.to/movie/chef-16934" },
      { title: "The Lego Movie", genre: "Animation/Comedy", link: "https://myflixerz.to/movie/the-lego-movie-19304" },
      { title: "Love Actually", genre: "Romantic Comedy", link: "https://myflixerz.to/movie/love-actually-19035" },
      { title: "Finding Nemo", genre: "Animation/Adventure", link: "https://myflixerz.to/movie/finding-nemo-19561" },
      { title: "Matilda", genre: "Family/Fantasy/Comedy", link: "https://myflixerz.to/movie/matilda-18736" },
      { title: "The Pursuit of Happyness", genre: "Biography/Drama", link: "https://myflixerz.to/movie/the-pursuit-of-happyness-19175" },
      { title: "Ratatouille", genre: "Animation/Comedy", link: "https://myflixerz.to/movie/ratatouille-19398" },
      { title: "About Time", genre: "Romance/Drama/Comedy", link: "https://myflixerz.to/movie/about-time-19112" },
      { title: "Forrest Gump", genre: "Comedy/Drama", link: "https://myflixerz.to/movie/forrest-gump-19710" }
    ]
  }
  ,
  Good:{
    quotes: [
      "Let peace settle gently in your soul.(let it hibernate)",
      "You’re exactly where you need to be.",
      "Let contentment fill your cup.(chocolate milk too)",
      "Every step forward is a step worth celebrating.(🕺)",
      "Let your mind rest in the present.",
      "You are enough, just as you are.",
      "Simple joys make the best memories.",
      "Trust the journey, even on quiet roads.",
      "Good things grow with patience.",
      "Let your heart be light.(💡)",
      "Savor the gentle moments.",
      "Let hope be your compass.",
      "Find beauty in the everyday.",
      "You’re doing better than you think.",
      "Let your thoughts be gentle.(impossible?)",
      "A calm mind is a powerful mind.",
      "Please dont torture anyone today😭",
      "you should probably call out nish on that phasmophobia match again!",
      "you should annoy someone for better mood"
    ],
    songs: [
      { title: "Japanese denim - Daniel Caesar", cover: "./coverimages/dc1.png", link: "https://open.spotify.com/track/7IVukH71OXfAu3KudrrizN?si=201c1cdb615142f8" },
      { title: "Say It Right – Nelly Furtado", cover: "./coverimages/nf1.png", link: "https://open.spotify.com/track/2aI21FnmY7TJVKeMaoQZ0t?si=c9193e1f6b834acc" },
      { title: "Wu Ji (Theme Song) – Xiao Zhan and Wang Yibo", cover: "./coverimages/xz1.png", link: "https://open.spotify.com/track/0iIwgC2UYdfRzPloo53huH?si=90cfa72153ce41b6" },
      { title: "Waltzing in the Rain – Vincent Diamanta", cover: "./coverimages/vd1.png", link: "https://open.spotify.com/track/3lv1OMbvmODFykWOboFSKt?si=cb73bb67644e4041" },
      { title: "Peperomia Seedling - Green House", cover: "./coverimages/gh1.png", link: "https://open.spotify.com/track/5Gly7CIj29ZKPw5Zo0qFmz?si=3eb51617364b4a43" },
      { title: "No2 – RM", cover: "./coverimages/rm1.png", link: "https://open.spotify.com/track/2sXaFMTkBHYrEgfGJ2y27a?si=d8057e13d9794235" },
      { title: "Free Woman – MARINA", cover: "./coverimages/marina2.png", link: "https://open.spotify.com/track/24u7H6M4C4YeOjAMdMVsGv?si=60fb9ce62c1d468e" },
      { title: "Answer: Love Myself – BTS", cover: "./coverimages/bts1.png", link: "https://open.spotify.com/track/2X3UgVLSA4wYriGIQyYmMA?si=663cf600fc2448d5" },
      { title: "Comfort Crowd – Conan Gray", cover: "./coverimages/cg1.png", link: "https://open.spotify.com/track/6uaBrivDHCaV0uBTiwHTUi?si=73a8596eb5d141fb" },
      { title: "Handmade Heaven – MARINA", cover: "./coverimages/marina3.png", link: "https://open.spotify.com/track/554KgAoTw8cGS40oSbmTeG?si=e507a3530392463b" },
      { title: "The Greatest – Sia", cover: "./coverimages/sia1.png", link: "https://open.spotify.com/track/6bLopGnirdrilrpdVB6Um1?si=d2ba1c92c9bb4a8a" },
      { title: "Primadonna – MARINA", cover: "./coverimages/marina1.png", link: "https://open.spotify.com/track/4AuNt2oAsF4VErT7Fo3IRH?si=24ac231dc3164f2d" },
      { title: "I Love You But I Love Me More – MARINA", cover: "./coverimages/marina2.png", link: "https://open.spotify.com/track/0jYC7cHrJUtC8oLdFqjtrS?si=c9642285ae3a4adb" },
      { title: "God Is a Woman – Ariana", cover: "./coverimages/ag1.png", link: "https://open.spotify.com/track/5OCJzvD7sykQEKHH7qAC3C?si=f1da6691c65849f2" },
      { title: "Keeping the Light On – Joy Oladokun", cover: "./coverimages/jo1.png", link: "https://open.spotify.com/track/1Uacdg0eFpE2bpjS90feZQ?si=97e8514fd7a14acc" },
      { title: "Put Your Records On – Corinne Bailey Rae", cover: "./coverimages/cbr1.png", link: "https://open.spotify.com/track/2nGFzvICaeEWjIrBrL2RAx?si=a4b87ba56e2b4581" },
      { title: "Kiss Me – Sixpence None the Richer", cover: "./coverimages/snr1.png", link: "https://open.spotify.com/track/754kgU5rWscRTfvlsuEwFp?si=67414f1dc5894fb5" },
      { title: "There She Goes – The La's", cover: "./coverimages/las1.png", link: "https://open.spotify.com/track/4c6vZqYHFur11FbWATIJ9P?si=76df437ee4244d38" },
      { title: "All Night – BTS", cover: "./coverimages/Bts4.png", link: "https://open.spotify.com/track/4sfXQzbYjROMuEgDfJisj3?si=f9027c727fd9446d" }
    ],
    movies: [
      { title: "The Secret Life of Walter Mitty", genre: "Adventure/Comedy/Drama", link: "https://myflixerz.to/movie/the-secret-life-of-walter-mitty-18800" },
      { title: "The Hundred-Foot Journey", genre: "Drama/Comedy", link: "https://myflixerz.to/movie/the-hundredfoot-journey-17896" },
      { title: "The Sound of Music", genre: "Musical/Drama", link: "https://myflixerz.to/movie/the-sound-of-music-17960" },
      { title: "Big Fish", genre: "Fantasy/Drama", link: "https://myflixerz.to/movie/big-fish-18566" },
      { title: "The Help", genre: "Drama", link: "https://myflixerz.to/movie/the-help-18385" },
      { title: "The King’s Speech", genre: "Biography/Drama", link: "https://myflixerz.to/movie/the-kings-speech-19179" },
      { title: "A Beautiful Mind", genre: "Biography/Drama", link: "https://myflixerz.to/movie/a-beautiful-mind-18913" },
      { title: "Life Is Beautiful", genre: "Comedy/Drama", link: "https://myflixerz.to/movie/life-is-beautiful-19237" },
      { title: "Mary Poppins", genre: "Musical/Family", link: "https://myflixerz.to/movie/mary-poppins-19232" },
      { title: "October Sky", genre: "Biography/Drama", link: "https://myflixerz.to/movie/october-sky-53941" },
      { title: "Pay It Forward", genre: "Drama", link: "https://myflixerz.to/movie/pay-it-forward-11855" },
      { title: "The Bucket List", genre: "Comedy/Drama", link: "https://myflixerz.to/movie/the-bucket-list-11996" },
      { title: "Wonder", genre: "Drama/Family", link: "https://myflixerz.to/movie/wonder-19310" },
      { title: "Remember the Titans", genre: "Biography/Drama", link: "https://myflixerz.to/movie/remember-the-titans-17383" },
      { title: "Billy Elliot", genre: "Drama/Music", link: "https://myflixerz.to/movie/billy-elliot-17589" },
      { title: "The Peanut Butter Falcon", genre: "Adventure/Drama", link: "https://myflixerz.to/movie/the-peanut-butter-falcon-40921" },
      { title: "Good Will Hunting", genre: "Drama", link: "https://myflixerz.to/movie/good-will-hunting-18982" },
      { title: "The Perks of Being a Wallflower", genre: "Drama/Romance", link: "https://myflixerz.to/movie/the-perks-of-being-a-wallflower-18953" },
      { title: "Hidden Figures", genre: "Biography/Drama", link: "https://myflixerz.to/movie/hidden-figures-19560" }
    ]
},
Sad: {
    quotes: [
      "It’s okay to feel down, brighter days are coming.",
      "Even the darkest night ends with dawn.",
      "You are stronger than this moment (DEFINITELY)",
      "Let your heart rest,healing takes time.",
      "Storms help you appreciate the sunshine.",
      "Gentle thoughts for a heavy heart.(AND HUGS)",
      "Let yourself feel, and let yourself heal.",
      "Every tear is a step toward healing.",
      "You matter, even on your hardest days.",
      "Hold on hope is quietly growing.",
      "Let comfort find you in small things.",
      "Your feelings are valid and important.",
      "This too shall pass.",
      "Let kindness start with yourself.",
      "You are braver than you believe.",
      "Sadness is real, but so is hope.(and so is the masala dosa)",
      "Let tomorrow bring new light.",
      "you should watch your comfort shows today",
      "sleep is the way today!!!",
      "how about you watch more of smosh",
      "u should watch run jin"
    ],
    songs: [
      { title: "Not Strong Enough – boygenius, Julien Baker", cover: "./coverimages/bjb1.png", link: "https://open.spotify.com/track/09DR0sHnQUhHOiSNttc1mv?si=3bbf94f6e3194642" },
      { title: "To Be Alone – Hozier", cover: "./coverimages/h1.png", link: "https://open.spotify.com/track/0fEKxq1mghyT0b867l4Jaf?si=fb19c2eda9cf4c12" },
      { title: "Invisible – Skylar Grey", cover: "./coverimages/sg1.png", link: "https://open.spotify.com/track/2OXHF0zVr2TSqhpm80PS1P?si=888b3415bec54d71" },
      { title: "Mystery of Love – Sufjan Stevens", cover: "./coverimages/ss1.png", link: "https://open.spotify.com/track/4HbeGjbt7u3pvwDk1vN7P0?si=c6589d9a2df4445a" },
      { title: "Le Cygne – Camille Saint-Saëns", cover: "./coverimages/css1.png", link: "https://open.spotify.com/track/59eTbibtvvBIGj27eN3zqq?si=2347770a71e8444b" },
      { title: "Change pt2 – RM", cover: "./coverimages/rm1.png", link: "https://open.spotify.com/track/2hMvhh9FiCB6njOYR7tkT8?si=acae649d389a4c76" },
      { title: "Like Crazy – Jimin", cover: "./coverimages/jimin1.png", link: "https://open.spotify.com/track/3Ua0m0YmEjrMi9XErKcNiR?si=6d16388dd6c24be2" },
      { title: "Your Existence – Wonstein", cover: "./coverimages/ws1.png", link: "https://open.spotify.com/track/2tmX4T7ODY34NwvQ3DD3MC?si=d371e35273314f0b" },
      { title: "Dear Arkansas Daughter – Lady Lamb", cover: "./coverimages/ll1.png", link: "https://open.spotify.com/track/3MOFjpuUDhYCAXYcjYb3FI?si=c220f32d12034ea3" },
      { title: "The Moon Will Sing – The Crane Wives", cover: "./coverimages/cw1.png", link: "https://open.spotify.com/track/4v0Zqmuhlbt5nCj712Y26n?si=4a78f8728dda43dd" },
      { title: "Vampire Empire – Big Thief", cover: "./coverimages/bt1.png", link: "https://open.spotify.com/track/4SwSpxsOYtnEaRxWtYrnvZ?si=e2745f60946b4540" },
      { title: "Curses – The Crane Wives", cover: "./coverimages/cw2.png", link: "https://open.spotify.com/track/5PqUrRRbNsjMCM2o61istC?si=52f7ffbf73e54d1c" },
      { title: "Ship in a Bottle – fin", cover: "./coverimages/fin1.png", link: "https://open.spotify.com/track/7EioHGLoCcjuIgQwKh8O8H?si=6ff392d7d95e411f" },
      { title: "Driving Myself Home – Rose Betts", cover: "./coverimages/rb1.png", link: "https://open.spotify.com/track/2dX8DvGkFb33vE7GJryiyP?si=64d4bd9fd7514743" },
      { title: "All I Ever Asked – Rachel Chinouriri", cover: "./coverimages/rc1.png", link: "https://open.spotify.com/track/2F9DCIJ7ZXHhNkiIlIIOkw?si=c34f6df0255a45a2" },
      { title: "Never Love an Anchor – The Crane Wives", cover: "./coverimages/cw1.png", link: "https://open.spotify.com/track/7JLm1z8cu49xpXPO1TdZnG?si=05502d468a854018" },
      { title: "Swim With Sam – A Balladeer", cover: "./coverimages/bal1.png", link: "https://open.spotify.com/track/7HWxIBizOFNo505Ljw6IcV?si=5dd0a6b2c94447c0" },
      { title: "Winter Flower – Younha/RM", cover: "./coverimages/y_r1.png", link: "https://open.spotify.com/track/4Eefey3uN90Abhbr47zKmC?si=58fd8996f5d94f19" },
      { title: "uhgood – RM", cover: "./coverimages/rm2.png", link: "https://open.spotify.com/track/5u9Pr2CujzeWFZJPALBPqQ?si=e2f75a79e1964f64" },
      { title: "Tokyo – RM", cover: "./coverimages/rm2.png", link: "https://open.spotify.com/track/2YCTRzLwXgiNvbod8xuCHl?si=60d3b6c333f64ae0" }
    ],
    movies: [
      { title: "The Fault in Our Stars", genre: "Romance/Drama", link: "https://myflixerz.to/movie/the-fault-in-our-stars-18754" },
      { title: "Bridge to Terabithia", genre: "Family/Drama/Fantasy", link: "https://myflixerz.to/movie/bridge-to-terabithia-18242" },
      { title: "My Girl", genre: "Drama/Romance", link: "https://myflixerz.to/movie/my-girl-16876" },
      { title: "Marley & Me", genre: "Comedy/Drama", link: "https://myflixerz.to/movie/marley-and-me-17676" },
      { title: "Atonement", genre: "Drama/Romance/War", link: "https://myflixerz.to/movie/atonement-17626" },
      { title: "Hachi: A Dog’s Tale", genre: "Family/Drama", link: "https://myflixerz.to/movie/hachi-a-dogs-tale-18468" },
      { title: "The Green Mile", genre: "Crime/Drama/Fantasy", link: "https://myflixerz.to/movie/the-green-mile-19395" },
      { title: "The Lion King", genre: "Animation/Drama/Adventure", link: "https://myflixerz.to/movie/the-lion-king-5872" },
      { title: "Grave of the Fireflies", genre: "Animation/War/Drama", link: "https://myflixerz.to/movie/grave-of-the-fireflies-67215" },
      { title: "Million Dollar Baby", genre: "Drama/Sport", link: "https://myflixerz.to/movie/million-dollar-baby-18986" },
      { title: "The Lovely Bones", genre: "Drama/Fantasy", link: "https://myflixerz.to/movie/the-lovely-bones-18189" },
      { title: "Manchester by the Sea", genre: "Drama", link: "https://myflixerz.to/movie/manchester-by-the-sea-18436" },
      { title: "Eternal Sunshine of the Spotless Mind", genre: "Romance/Drama/Sci-Fi", link: "https://myflixerz.to/movie/eternal-sunshine-of-the-spotless-mind-19135" },
      { title: "Schindler’s List", genre: "Biography/Drama/History", link: "https://myflixerz.to/movie/schindlers-list-19786" },
      { title: "The Notebook", genre: "Romance/Drama", link: "https://myflixerz.to/movie/the-notebook-19489" },
      { title: "Requiem for a Dream", genre: "Drama", link: "https://myflixerz.to/movie/requiem-for-a-dream-10288" },
      { title: "Blue Valentine", genre: "Romance/Drama", link: "https://myflixerz.to/movie/blue-valentine-16106" },
      { title: "The Boy in the Striped Pajamas", genre: "War/Drama", link: "https://myflixerz.to/movie/the-boy-in-the-striped-pyjamas-18633" },
      { title: "My Sister’s Keeper", genre: "Drama", link: "https://myflixerz.to/movie/my-sisters-keeper-57935" }
    ]
  },
  VerySad: {
    quotes: [
      "It’s okay to rest when the world feels heavy.(HIBERNATION)",
      "You are not alone, even when it feels that way.",
      "There is strength in asking for help.",
      "One breath at a time is enough.",
      "You are worthy of love, especially now.",
      "The night may feel endless, but morning always comes.",
      "You are still here, and that is enough.",
      "Let hope be a quiet whisper in your heart.",
      "You are allowed to feel broken and still be whole.",
      "Let gentle thoughts hold you together.",
      "Your story isn’t over yet.",
      "Even small steps are steps forward.",
      "You are seen, you are valued.",
      "May you find peace, even in fragments.",
      "Let tomorrow bring a softer day.",
      "YOU NEED EPIGAMIA CHOCOLATE MILK",
      "Sending hugs🫂",
      "maybe u should take out your tarot cards",
      "YOU ARE APPRECIATED <3"

    ],
    songs: [
      { title: "People, I've Been Sad – Christine and the Queens", cover: "./coverimages/cq1.png", link: "https://open.spotify.com/track/2rWeNybwVZTWEbkb9JOjcz?si=c2d18b0247b5441c" },
      { title: "idontwannabeyouanymore – Billie Eilish", cover: "./coverimages/be1.png", link: "https://open.spotify.com/track/41zXlQxzTi6cGAjpOXyLYH?si=72f119afaa794efb" },
      { title: "Teen Idle – MARINA", cover: "./coverimages/marina1.png", link: "https://open.spotify.com/track/5B8N5rPOmTVVGpuBMK2Vby?si=61298bbfb2904f7b" },
      { title: "Numb – Linkin Park", cover: "./coverimages/lp1.png", link: "https://open.spotify.com/track/2ULknvs2DJ0L0hLRDYunor?si=17a06d31526d4c4c" },
      { title: "Creep – Radiohead", cover: "./coverimages/rh1.png", link: "https://open.spotify.com/track/70LcF31zb1H0PyJoS1Sx1r?si=d9cd358e34e44095" },
      { title: "Sabry Aalil – Sherine", cover: "./coverimages/s1.png", link: "https://open.spotify.com/track/7qLXBcYW78is9LygQBziAU?si=753ce888d5004983" },
      { title: "Trivia 轉: Seesaw – BTS", cover: "./coverimages/bts1.png", link: "https://open.spotify.com/track/0mZI1NpihIVcho2f9MmqSW?si=ce55724b9c994730" },
      { title: "People – Agust D", cover: "./coverimages/agustd2.png", link: "https://open.spotify.com/track/6HDHaCnH2FCSdEwXrJfEVF?si=7b7cba0f392d434a" },
      { title: "Let Go – BTS", cover: "./coverimages/Bts5.png", link: "https://open.spotify.com/track/1OqDvYVDhJyFZny7XlfIyZ?si=0ae8d4ee9dbc4c82" },
      { title: "Reflection – BTS", cover: "./coverimages/Bts6.png", link: "https://open.spotify.com/track/6O7358UPKsUumzjumFxVtp?si=2194e5a738b548a8" },
      { title: "Blue & Grey – BTS", cover: "./coverimages/Bts7.png", link: "https://open.spotify.com/track/7Ki0hse0IfXEcXUlpyECbJ?si=e3bf5f5e285d4b9d" },
      { title: "Black Pearl – Sunmi", cover: "./coverimages/sun1.png", link: "https://open.spotify.com/track/5SEh5ElnuNTz6zn8Th5pP9?si=36b5cd05fb2b4e0f" },
      { title: "People Watching – Conan Gray", cover: "./coverimages/cg2.png", link: "https://open.spotify.com/track/3TFoEJe5zNuHZStRboWPxg?si=7140cf49ddf04983" },
      { title: "Lent – Autoheart", cover: "./coverimages/ah1.png", link: "https://open.spotify.com/track/3eonvnYEnoZHwmfTQrGf0q?si=9fff482ab3224ac0" },
      { title: "Linger – The Cranberries", cover: "./coverimages/tc1.png", link: "https://open.spotify.com/track/0gEyKnHvgkrkBM6fbeHdwK?si=e78dcf5ee5a042ff" },
      { title: "Amygdala – Agust D", cover: "./coverimages/agustd1.png", link: "https://open.spotify.com/track/5fj32MKLHkut2Vod1UodcU?si=ab0503af5fd64c17" },
      { title: "Seoul – RM", cover: "./coverimages/rm2.png", link: "https://open.spotify.com/track/1sKsYTGy8XfHjCYqcudqG5?si=8d1a6313617048c6" },
      { title: "badbye – RM", cover: "./coverimages/rm2.png", link: "https://open.spotify.com/track/6CYJojwhuUyTTL5G6AsDHf?si=fb196d8b93444f66" },
      { title: "Lonely – RM", cover: "./coverimages/rm1.png", link: "https://open.spotify.com/track/49iPCmLYg3SS8r2MXcbR1N?si=a32862fe550c409b" },
      { title: "Line Without a Hook - Rick Montgomery", cover: "./coverimages/rmg1.png", link: "https://open.spotify.com/track/5NvOZCjZaGGGL597exlQWv?si=7d2a1edfe18546a0" }
    ],
    movies: [
      { title: "Room", genre: "Drama/Thriller", link: "https://myflixerz.to/movie/room-17491" },
      { title: "Precious", genre: "Drama", link: "https://myflixerz.to/movie/precious-13152" },
      { title: "The Fault in Our Stars", genre: "Romance/Drama", link: "https://myflixerz.to/movie/the-fault-in-our-stars-18754" },
      { title: "The Road", genre: "Drama/Adventure", link: "https://myflixerz.to/movie/the-road-17509" },
      { title: "Lion", genre: "Biography/Drama", link: "https://myflixerz.to/movie/lion-19485" },
      { title: "The Imitation Game", genre: "Biography/Drama/Thriller", link: "https://myflixerz.to/movie/the-imitation-game-19720" },
      { title: "12 Years a Slave", genre: "Biography/Drama/History", link: "https://myflixerz.to/movie/12-years-a-slave-19388" },
      { title: "The Pianist", genre: "Biography/Drama/War", link: "https://myflixerz.to/movie/the-pianist-19205" },
      { title: "Dancer in the Dark", genre: "Drama/Musical/Crime", link: "https://myflixerz.to/movie/dancer-in-the-dark-17148" },
      { title: "Mystic River", genre: "Crime/Drama/Mystery", link: "https://myflixerz.to/movie/mystic-river-18671" },
      { title: "The Lovely Bones", genre: "Drama/Fantasy", link: "https://myflixerz.to/movie/the-lovely-bones-18189" },
      { title: "Hotel Rwanda", genre: "Biography/Drama/History", link: "https://myflixerz.to/movie/hotel-rwanda-16628" },
      { title: "Brokeback Mountain", genre: "Romance/Drama", link: "https://myflixerz.to/movie/brokeback-mountain-17584" },
      { title: "The Untamed", genre: "Drama/Boys Love/Comedy/Sci-fi", link: "https://wetv.vip/en/play/gnwjazjgmg997xg/d0031smeq8n-EP01%3A_The_Untamed" },
      { title: "New girl", genre: "Comedy", link: "https://myflixerz.to/tv/new-girl-39364" },
      { title: "Fleabag", genre: "Comedy/Drama", link: "https://myflixerz.to/tv/fleabag-37117" },
      { title: "Derry Girls", genre: "Comedy", link: "https://myflixerz.to/tv/derry-girls-37473" },
      { title: "Arcane", genre: "Sci-fi/Fantasy", link: "https://myflixerz.to/tv/arcane-73990" }

    ]
  },
  Mad: {
    quotes: [
      "Let your anger fuel positive change.",
      "Breathe deep, you are bigger than your frustration.(even bigger than whats bothering u)",
      "Channel your fire into something good.",
      "Let your voice be strong and kind.",
      "You have the power to choose your response.",
      "Anger is energy,transform it into action.(kill that oldie in front of ur balcony /j)",
      "Let calm be your comeback.",
      "You control the storm within.",
      "Pause, breathe, and rise above.(not in the clouds)",
      "You are more than this moment of anger.",
      "Let patience be your superpower.",
      "Speak your truth with compassion.",
      "Let your heart lead, not your temper.",
      "You can turn frustration into focus.",
      "Let your mind be the master of your mood.",
      "Even in anger, choose kindness.",
      "Let peace be your protest.",
      "You are resilient, even when challenged.",
      "Let go of what you can’t control.",
      "please dont kill someone"

    ],
    songs: [
      { title: "Motion Sickness – Phoebe Bridgers", cover: "./coverimages/pb1.png", link: "https://open.spotify.com/track/25Syi9wnfn6ZGAmiOBypPq?si=e4925a2e998043fa" },
      { title: "Show and Tell – Melanie Martinez", cover: "./coverimages/mm1.png", link: "https://open.spotify.com/track/7po7c8LzxTZ0ybU41qT5gD?si=f27d48842d8f4471" },
      { title: "Judas – Lady Gaga", cover: "./coverimages/lg2.png", link: "https://open.spotify.com/track/7F25roCtYi55JouckaayPC?si=98991742e0d343c2" },
      { title: "Dis-ease – BTS", cover: "./coverimages/Bts7.png", link: "https://open.spotify.com/track/0hxeouHqP3qzpTHerA7ha2?si=11602dcdb1bd4300" },
      { title: "Paint the Town Red – Doja Cat", cover: "./coverimages/djc1.png", link: "https://open.spotify.com/track/2IGMVunIBsBLtEQyoI1Mu7?si=a6dc4c65bcbf47ab" },
      { title: "Boss Bitch – Doja Cat", cover: "./coverimages/djc2.png", link: "https://open.spotify.com/track/78qd8dvwea0Gosb6Fe6j3k?si=4d2408fb856c4867" },
      { title: "Venus Flytrap – MARINA", cover: "./coverimages/marina2.png", link: "https://open.spotify.com/track/6h7AmUi3ghBeEfsZygAxOd?si=4881fec73616482c" },
      { title: "I'm Not a Woman, I'm a God - Halsey", cover: "./coverimages/hs1.png", link: "https://open.spotify.com/track/5RhFmJifQe83FpQ6ZFFTZ5?si=39de2f3463c54e9b" },
      { title: "Poker Face – Lady Gaga", cover: "./coverimages/lg3.png", link: "https://open.spotify.com/track/1QV6tiMFM6fSOKOGLMHYYg?si=29c3188516be4939" },
      { title: "Toxic – Britney Spears", cover: "./coverimages/bs1.png", link: "https://open.spotify.com/track/6I9VzXrHxO9rA9A5euc8Ak?si=9d02b11bea2c4611" },
      { title: "Dangerous Woman – Ariana Grande", cover: "./coverimages/ag2.png", link: "https://open.spotify.com/track/3nef5W8jTkXrOKgCu4kmq7?si=fae183723e214598" },
      { title: "Lilith – Halsey and SUGA", cover: "./coverimages/h2.png", link: "https://open.spotify.com/track/3l6LBCOL9nPsSY29TUY2VE?si=051a39b500294396" },
      { title: "Pied Piper – BTS", cover: "./coverimages/Bts8.png", link: "https://open.spotify.com/track/1ZPeaPDjQOOC8hw1mNjyjF?si=5de5f06308fb41c2" },
      { title: "That's My Girl – Fifth Harmony", cover: "./coverimages/fh1.png", link: "https://open.spotify.com/track/2ACOWPLUe4A4KuQ5ioD2od?si=b750fe56cfe64837" },
      { title: "Circus – Britney Spears", cover: "./coverimages/bs2.png", link: "https://open.spotify.com/track/7jk7gqyEonmVVYahZN5zhW?si=036b0c5f532d4f30" },
      { title: "Harpy Hare – Yaekolore", cover: "./coverimages/yk1.png", link: "https://open.spotify.com/track/6pWlv50Lthad8jyd6f1TlC?si=e1876a6ee3464f1a" },
      { title: "Huh?! – Agust D", cover: "./coverimages/agustd1.png", link: "https://open.spotify.com/track/6XrPzwKeGzEvtan3acn7VH?si=abe0be3108874f32" },
      { title: "Give It To Me – Agust D", cover: "./coverimages/agustd3.png", link: "https://open.spotify.com/track/1m0yEldZVNu9SzmtqfFWRt?si=170a7f593e3245b0" },
      { title: "Hectic – RM", cover: "./coverimages/rm1.png", link: "https://open.spotify.com/track/3ZCuqvHYhjDlliRH9oCs77?si=845755b832df4977" },
      { title: "Daechwita – Agust D", cover: "./coverimages/agustd2.png", link: "https://open.spotify.com/track/0JKGe340YJwfDrpXqPQ8sw?si=d754ad79bb064ec9" }
    ],
    movies: [
      { title: "Jennifers Body", genre: "Comedy/Horror", link: "https://myflixerz.to/movie/jennifers-body-18190" },
      { title: "Peppermint", genre: "Action/Thriller/Drama", link: "https://myflixerz.to/movie/peppermint-19704" },
      { title: "Atomic Blonde", genre: "Action/Mystery/Thriller", link: "https://myflixerz.to/movie/atomic-blonde-19332" },
      { title: "The Long Kiss Goodnight", genre: "Crime/Action/Mystery/Thriller", link: "https://myflixerz.to/movie/the-long-kiss-goodnight-17200" },
      { title: "Kill Bill (Vol 1)", genre: "Action/Crime", link: "https://myflixerz.to/movie/kill-bill-vol-1-19131" },
      { title: "Kill Bill (Vol 2)", genre: "Action/Crime/Thriller", link: "https://myflixerz.to/movie/kill-bill-vol-2-18862" },
      { title: "The Favourite", genre: "Drama/History/Comedy", link: "https://myflixerz.to/movie/the-favourite-19833" },
      { title: "Gone Girl", genre: "Mystery/Thriller/Drama", link: "https://myflixerz.to/movie/gone-girl-19717" },
      { title: "Hard Candy", genre: "Drama/Thriller", link: "https://myflixerz.to/movie/hard-candy-17402" },
      { title: "Thoroughbreds", genre: "Thriller/Drama", link: "https://myflixerz.to/movie/thoroughbreds-16554" },
      { title: "Ready or Not", genre: "Horror/Comedy/Thriller/Mystery", link: "https://myflixerz.to/movie/ready-or-not-45352" },
      { title: "A Vigilante", genre: "Thriller/Drama", link: "https://myflixerz.to/movie/a-vigilante-14489" },
      { title: "Little Women", genre: "Comedy/Romance", link: "https://myflixerz.to/movie/little-women-41704" },
      { title: "Even lambs have teeth", genre: "Horror/Thriller", link: "https://myflixerz.to/movie/even-lambs-have-teeth-55020" },
      { title: "The Nightingale", genre: "Drama/Adventure/Thriller", link: "https://myflixerz.to/movie/the-nightingale-6360" },
      { title: "Ballerina", genre: "Action/Crime/Thriller", link: "https://myflixerz.to/movie/ballerina-101179" },
      { title: "", genre: "", link: "" },
      { title: "", genre: "", link: "" },
      { title: "", genre: "", link: "" },
      { title: "", genre: "", link: "" }
    ]
  },
  "really sad": {
    quotes: ["U should really get into detective work!!!!",
      "How'd you even find this?! You're a certified seeker.",
      "You nosy lil explorer",
      "Wait—how did you find this?",
      "You clicked the void and the void clicked back.",
      "Give thyself a cookie, mighty adventurer",
      "DAMN U FOUND THIS?? UR REWARD IS BULLY NISH PASS",
      "Honestly, i didn’t think anyone would find this.",
      

    ],
    songs: [],
    movies: [
      {
        title: "Run-Jin Ep 1",
        link: "https://youtu.be/NJhoWnlRECw?si=k3vdWnyEOeGAlidN",
      },
      {
        title: "Run-Jin Ep 2",
        link: "https://youtu.be/ybBPvd5Qt_M?si=yRCMQvJMyCgyhgkS",
      },
      {
        title: "Run-Jin Ep 3",
        link: "https://youtu.be/zm42SXCpuSo?si=thYRFTQy2zBLmpp-",
      },
      {
        title: "Run-Jin Ep 4",
        link: "https://youtu.be/JliAZvhJpl8?si=JGiJpJaJyvnXflsO",
      },
      {
        title: "Run-Jin Ep 5",
        link: "https://youtu.be/v5rUGagE910?si=ywj8tBi8vGgjguVm",
      },
      {
        title: "Run-Jin Ep 6",
        link: "https://youtu.be/0uoVYPw4hf4?si=xEius8agHV2J5CUQ",
      },
      {
        title: "Run-Jin Ep 7",
        link: "https://youtu.be/HjF32v4uFXw?si=xBtfFm52n9i-vfb3",
      },
      {
        title: "Run-Jin Ep 8",
        link: "https://youtu.be/Jvn4PtnzX44?si=wmw3lM0w1wLX4jnz",
      },
      {
        title: "Run-Jin Ep 9",
        link: "https://youtu.be/ytaopkxZUmU?si=ju3tBXkkUaSH20tU",
      },
      {
        title: "Run-Jin Ep 10",
        link: "https://youtu.be/o799SNn4eTU?si=ZC-THi1uAjjs2y_2",
      },
      {
        title: "Run-Jin Ep 11",
        link: "https://youtu.be/Xozj294ILP8?si=Q9VYZVWNJ0aAKxis",
      },
      {
        title: "Run-Jin Ep 12",
        link: "https://youtu.be/na6LvaQhCQk?si=VLNuqZsUNr0D5lwS",
      },
      {
        title: "Run-Jin Ep 13",
        link: "https://youtu.be/Stwau2ND_fo?si=-vY9zRtWl342cD0l",
      },
      {
        title: "Run-Jin Ep 14",
        link: "https://youtu.be/EzJaR8QL0q4?si=SMBJdWqwJPtRVVL2",
      },
      {
        title: "Run-Jin Ep 15",
        link: "https://youtu.be/SBjbstFEYtA?si=pnoICdbiduVGp6du",
      },
      {
        title: "Run-Jin Ep 16",
        link: "https://youtu.be/nnO1o6TYhaM?si=2y40v4sYdQ_aV03t",
      },
      {
        title: "Run-Jin Ep 17",
        link: "https://youtu.be/whJJzrKE65g?si=fMuRHP-LqK2WST-Q",
      },
      {
        title: "Run-Jin Ep 18",
        link: "https://youtu.be/D0HRrxipY_Y?si=6n-atoT0qcpn660X",
      },
      {
        title: "Run-Jin Ep 19",
        link: "https://youtu.be/ySb4CteETSk?si=hXBeBsk4SG2xEGRH",
      },
      {
        title: "Run-Jin Ep 20",
        link: "https://youtu.be/a3sNjokvUI4?si=VS9PVpOC6tbgGhsL",
      },
      {
        title: "Run-Jin Ep 21",
        link: "https://youtu.be/tweKMEEFYks?si=uYij3PPRAJEY7JVL",
      },
      {
        title: "Run-Jin Ep 22",
        link: "https://youtu.be/N6SBPaCYhV4?si=Epj9yK3t1XyZdNqS",
      },
      {
        title: "Run-Jin Ep 23",
        link: "https://youtu.be/XFfu0mjKW0k?si=ubimFs91bBtWqVWY",
      },
      {
        title: "Run-Jin Ep 24",
        link: "https://youtu.be/A2oK2xPvJV0?si=NiNuwRxRc4KOlDwq",
      },
      {
        title: "Run-Jin Ep 25",
        link: "https://youtu.be/CMXCZAJR1aU?si=FmGIVHP4VxZ_Y890",
      },
      {
        title: "Run-Jin Ep 26",
        link: "https://youtu.be/H5K-tSuTzyE?si=XFEtV-aKDGsLPGZp",
      },
      {
        title: "Run-Jin Ep 27",
        link: "https://youtu.be/yLnlO2PP4yA?si=kyB7fwCYr05iUR2i",
      },
      {
        title: "Run-Jin Ep 28",
        link: "https://youtu.be/4-bNoHb1zko?si=4zwELFXmb0gmizds",
      },
      {
        title: "Run-Jin Ep 29",
        link: "https://youtu.be/PGNkMjQmNc0?si=b3xRECHR_OnU6zvn",
      },
            {
        title: "Run-Jin Ep 30",
        link: "https://youtu.be/0_bkdqBvEjc?si=ixcEyk315MOdRJJx",
      },
      {
        title: "Run-Jin Ep 31",
        link: "https://youtu.be/6C5EkKlAJAY?si=Uzv23GK1zaMNbjOe",
      },
      {
        title: "Run-Jin Ep 32",
        link: "https://youtu.be/0k3BAYr-bdY?si=sq-m3RwVo31NvPLO",
      },
      {
        title: "Run-Jin Ep 33",
        link: "https://youtu.be/Gu5BkUji4HA?si=gZhL1kbpirxXoeLl",
      },
      {
        title: "Run-Jin Ep 34",
        link: "https://youtu.be/YLT3ZeuJMvE?si=llz_Wo4velSpz8Td",
      },
      {
        title: "Run-Jin Ep 35",
        link: "https://youtu.be/zk7DO9hhd7I?si=34oa6euAqkTD9rZ8",
      },
      {
        title: "Run-Jin Ep 36",
        link: "https://youtu.be/rhS2zJPgE24?si=gw42uNpHOPELuo6Q",
      },

    ]
  }


};

export default recommendations;
