const recommendations = {
  Happy: {
    quotes: [
      "Let your laughter light up the day.",
      "Happiness is the sunshine you carry inside.",
      "Dance with the breeze, sing with the trees.",
      "Every moment is a reason to smile.",
      "Let your heart skip with delight.",
      "Celebrate the little victories.",
      "Share your smile; it’s contagious.",
      "Life sparkles when you do.",
      "Let happiness be your favorite habit.",
      "Bright days are made by bright minds.",
      "Chase dreams with a full heart.",
      "Good vibes are your superpower.",
      "Choose joy, again and again.",
      "Let your spirit soar above the clouds.",
      "which soul are u planning on torturing today?",
      "Its a PERFECT day to have chcocolate milk."
    ],
    songs: [
      { title: "MIC Drop – BTS", cover: "./coverimages/Bts1.png", link: "https://open.spotify.com/track/01380RE6UfsPSdiUIwrCoH?si=a514193e414d4b3b" },
      { title: "IDOL – BTS", cover: "./coverimages/Bts1.png", link: "https://open.spotify.com/track/1e8J3XClxZbFmvIHLI8CE4?si=0d612cf5cb5747a0" },
      { title: "Blue Hour – TXT", cover: "./coverimages/txt1.png", link: "https://open.spotify.com/track/3ObPkJQAgjAhTwYvDhPrAW?si=7a972b31af234a55" },
      { title: "No Tears Left to Cry – Ariana Grande", cover: "./coverimages/ag1.png", link: "https://open.spotify.com/track/2qT1uLXPVPzGgFOx4jtEuo?si=9c581e1aed07491b" },
      { title: "Interlude – Agust D", cover: "./coverimages/agustd1.png", link: "https://open.spotify.com/track/56tf3cHQkwmvoplotk5QXd?si=7d5f3a6834da421c" },
      { title: "Trivia: Love – BTS", cover: "./coverimages/Bts1.png", link: "https://open.spotify.com/track/6bSwpQYEguyMlkCoWiBt3Y?si=62a355b832974538" },
      { title: "Love Maze – BTS", cover: "./coverimages/Bts2.png", link: "https://open.spotify.com/track/4ROdFnoZNn2RTmwct0cVpx?si=14ef636063754f62" },
      { title: "Euphoria – BTS", cover: "./coverimages/Bts1.png", link: "https://open.spotify.com/track/5YMXGBD6vcYP7IolemyLtK?si=349f8d53ecfd4adc" },
      { title: "Mikrokosmos – BTS", cover: "./coverimages/Bts3.png", link: "https://open.spotify.com/track/0jSccBRnhNU4KtACMQPvco?si=85a93bb201af463b" },
      { title: "Loser=Lover – TXT", cover: "./coverimages/txt2.png", link: "https://open.spotify.com/track/21aOLk12MksET8AsbU0SI6?si=9eae185b75024e40" },
      { title: "Pink Pony Club – Chappell Roan", cover: "./coverimages/cr1.png", link: "https://open.spotify.com/track/1k2pQc5i348DCHwbn5KTdc?si=12a24c5045d343e6" },
      { title: "Girls Just Want to Have Fun – Cyndi Lauper", cover: "./coverimages/cl1.png", link: "https://open.spotify.com/track/4y1LsJpmMti1PfRQV9AWWe?si=8000327caef545e0" },
      { title: "Bubblegum Bitch – MARINA", cover: "./coverimages/marina1.png", link: "https://open.spotify.com/track/6IbnUaczZBT34DhaD6S18F?si=dfb6285b032f4810" },
      { title: "Applause – Lady Gaga", cover: "./coverimages/lg1.png", link: "https://open.spotify.com/track/5ka2ajep9OAvU5Sgduhiex?si=493940c1924141b4" },
      { title: "How to Be a Heartbreaker – MARINA", cover: "./coverimages/marina1.png", link: "https://open.spotify.com/track/2sEk5R8ErGIFxbZ7rX6S2S?si=9c425b4f63254be9" },
      { title: "Naughty – Red Velvet", cover: "./coverimages/rv1.png", link: "https://open.spotify.com/track/0P8lbWigAHXPKxUG60xh79?si=a659692de2db4d26" },
      { title: "Looking at Me – Sabrina Carpenter", cover: "./coverimages/sb1.png", link: "https://open.spotify.com/track/59tskctgqUmjCWAwhzYAFm?si=01d27dd6570243dc" },
      { title: "Sweet Tooth – Scott Helman", cover: "./coverimages/sh1.png", link: "https://open.spotify.com/track/2qROUDWN1RCJoyiVSr6ifm?si=2e4a734c991d4c76" },
      { title: "Dream Song – Lala Lala", cover: "./coverimages/lala1.png", link: "https://open.spotify.com/track/0jTKmPYBGiEZsQtRNlWM1L?si=de2274f6455d4dbc" },
      { title: "Fairytale – Alexander Rybak", cover: "./coverimages/ar1.png", link: "https://open.spotify.com/track/3MnAsEBBsEj86d03RgO4EM?si=c9acdff0df2944cc" }
    ],
    movies: [
      { title: "The Intouchables", genre: "Comedy/Drama", link: "" },
      { title: "Amélie", genre: "Romantic Comedy", link: "" },
      { title: "Singin’ in the Rain", genre: "Musical/Comedy", link: "" },
      { title: "Paddington 2", genre: "Family/Comedy", link: "" },
      { title: "Up", genre: "Animation/Adventure", link: "" },
      { title: "Ferris Bueller’s Day Off", genre: "Teen/Comedy", link: "" },
      { title: "Little Miss Sunshine", genre: "Comedy/Drama", link: "" },
      { title: "The Grand Budapest Hotel", genre: "Comedy/Adventure", link: "" },
      { title: "School of Rock", genre: "Comedy/Music", link: "" },
      { title: "Julie & Julia", genre: "Comedy/Biography", link: "" },
      { title: "The Princess Bride", genre: "Fantasy/Adventure/Comedy", link: "" },
      { title: "Chef", genre: "Comedy/Drama", link: "" },
      { title: "The Lego Movie", genre: "Animation/Comedy", link: "" },
      { title: "Love Actually", genre: "Romantic Comedy", link: "" },
      { title: "Finding Nemo", genre: "Animation/Adventure", link: "" },
      { title: "Matilda", genre: "Family/Fantasy/Comedy", link: "" },
      { title: "The Pursuit of Happyness", genre: "Biography/Drama", link: "" },
      { title: "Ratatouille", genre: "Animation/Comedy", link: "" },
      { title: "About Time", genre: "Romance/Drama/Comedy", link: "" },
      { title: "Forrest Gump", genre: "Comedy/Drama", link: "" }
    ]
  }
  ,
  Good:{
    quotes: [
      "Let peace settle gently in your soul.",
      "You’re exactly where you need to be.",
      "Let contentment fill your cup.",
      "Every step forward is a step worth celebrating.",
      "Breathe in calm, exhale gratitude.",
      "Let your mind rest in the present.",
      "You are enough, just as you are.",
      "Simple joys make the best memories.",
      "Trust the journey, even on quiet roads.",
      "Good things grow with patience.",
      "Let your heart be light.",
      "Savor the gentle moments.",
      "Let hope be your compass.",
      "Find beauty in the everyday.",
      "You’re doing better than you think.",
      "Let your thoughts be gentle.",
      "A calm mind is a powerful mind."
    ],
    songs: [
      { title: "Japanese denim - Daniel Caesar", cover: "./coverimages/dc1.png", link: "https://open.spotify.com/track/7IVukH71OXfAu3KudrrizN?si=201c1cdb615142f8" },
      { title: "Say It Right – Nelly Furtado", cover: "./coverimages/nf1.png", link: "https://open.spotify.com/track/2aI21FnmY7TJVKeMaoQZ0t?si=c9193e1f6b834acc" },
      { title: "Wu Ji (Theme Song) – Xiao Zhan and Wang Yibo", cover: "./coverimages/xz1.png", link: "https://open.spotify.com/track/0iIwgC2UYdfRzPloo53huH?si=90cfa72153ce41b6" },
      { title: "Waltzing in the Rain – Vincent Diamanta", cover: "./coverimages/vd1.png", link: "https://open.spotify.com/track/3lv1OMbvmODFykWOboFSKt?si=cb73bb67644e4041" },
      { title: "Peperomia Seedling - Green House", cover: "./coverimages/gh1.png", link: "https://open.spotify.com/track/5Gly7CIj29ZKPw5Zo0qFmz?si=3eb51617364b4a43" },
      { title: "No2 – RM", cover: "./coverimages/rm1.png", link: "https://open.spotify.com/track/2sXaFMTkBHYrEgfGJ2y27a?si=d8057e13d9794235" },
      { title: "Free Woman – MARINA", cover: "./coverimages/marina2.png", link: "https://open.spotify.com/track/24u7H6M4C4YeOjAMdMVsGv?si=60fb9ce62c1d468e" },
      { title: "Answer: Love Myself – BTS", cover: "./coverimages/bts1.png", link: "https://open.spotify.com/track/2X3UgVLSA4wYriGIQyYmMA?si=663cf600fc2448d5" },
      { title: "Comfort Crowd – Conan Gray", cover: "./coverimages/cg1.png", link: "https://open.spotify.com/track/6uaBrivDHCaV0uBTiwHTUi?si=73a8596eb5d141fb" },
      { title: "Handmade Heaven – MARINA", cover: "./coverimages/marina3.png", link: "https://open.spotify.com/track/554KgAoTw8cGS40oSbmTeG?si=e507a3530392463b" },
      { title: "The Greatest – Sia", cover: "./coverimages/sia1.png", link: "https://open.spotify.com/track/6bLopGnirdrilrpdVB6Um1?si=d2ba1c92c9bb4a8a" },
      { title: "Primadonna – MARINA", cover: "./coverimages/marina1.png", link: "https://open.spotify.com/track/4AuNt2oAsF4VErT7Fo3IRH?si=24ac231dc3164f2d" },
      { title: "I Love You But I Love Me More – MARINA", cover: "./coverimages/marina2.png", link: "https://open.spotify.com/track/0jYC7cHrJUtC8oLdFqjtrS?si=c9642285ae3a4adb" },
      { title: "God Is a Woman – Ariana", cover: "", link: "" },
      { title: "Keeping the Light On – Joy Oladokun", cover: "", link: "" },
      { title: "Put Your Records On – Corinne Bailey Rae", cover: "", link: "" },
      { title: "Kiss Me – Sixpence None the Richer", cover: "", link: "" },
      { title: "There She Goes – The La's", cover: "", link: "" },
      { title: "All Night – BTS", cover: "", link: "" }
    ],
    movies: [
      { title: "The Secret Life of Walter Mitty", genre: "Adventure/Comedy/Drama", link: "" },
      { title: "The Hundred-Foot Journey", genre: "Drama/Comedy", link: "" },
      { title: "The Sound of Music", genre: "Musical/Drama", link: "" },
      { title: "Big Fish", genre: "Fantasy/Drama", link: "" },
      { title: "The Help", genre: "Drama", link: "" },
      { title: "The Blind Side", genre: "Biography/Drama", link: "" },
      { title: "The King’s Speech", genre: "Biography/Drama", link: "" },
      { title: "A Beautiful Mind", genre: "Biography/Drama", link: "" },
      { title: "Life Is Beautiful", genre: "Comedy/Drama", link: "" },
      { title: "Mary Poppins", genre: "Musical/Family", link: "" },
      { title: "October Sky", genre: "Biography/Drama", link: "" },
      { title: "Pay It Forward", genre: "Drama", link: "" },
      { title: "The Bucket List", genre: "Comedy/Drama", link: "" },
      { title: "Wonder", genre: "Drama/Family", link: "" },
      { title: "Remember the Titans", genre: "Biography/Drama", link: "" },
      { title: "Billy Elliot", genre: "Drama/Music", link: "" },
      { title: "The Peanut Butter Falcon", genre: "Adventure/Drama", link: "" },
      { title: "Good Will Hunting", genre: "Drama", link: "" },
      { title: "The Perks of Being a Wallflower", genre: "Drama/Romance", link: "" },
      { title: "Hidden Figures", genre: "Biography/Drama", link: "" }
    ]
},
Sad: {
    quotes: [
      "It’s okay to feel down; brighter days are coming.",
      "Even the darkest night ends with dawn.",
      "You are stronger than this moment”",
      "Let your heart rest; healing takes time.",
      "Storms help you appreciate the sunshine.",
      "Gentle thoughts for a heavy heart.",
      "Let yourself feel, and let yourself heal.",
      "Every tear is a step toward healing.",
      "You matter, even on your hardest days.",
      "Hold on; hope is quietly growing.",
      "Let comfort find you in small things.",
      "Your feelings are valid and important.",
      "This too shall pass.",
      "Let kindness start with yourself.",
      "You are braver than you believe.",
      "Sadness is real, but so is hope.",
      "Let tomorrow bring new light."
    ],
    songs: [
      { title: "Not Strong Enough – boygenius, Julien Baker", cover: "", link: "" },
      { title: "To Be Alone – Hozier", cover: "", link: "" },
      { title: "Invisible – Skylar Grey", cover: "", link: "" },
      { title: "Mystery of Love – Sufjan Stevens", cover: "", link: "" },
      { title: "Le Cygne – Camille Saint-Saëns", cover: "", link: "" },
      { title: "Change pt2 – RM", cover: "", link: "" },
      { title: "Like Crazy – Jimin", cover: "", link: "" },
      { title: "Your Existence – Wonstein", cover: "", link: "" },
      { title: "Dark Arkansas Daughter – Lady Lamb", cover: "", link: "" },
      { title: "The Moon Will Sing – The Crane Wives", cover: "", link: "" },
      { title: "Vampire Empire – Big Thief", cover: "", link: "" },
      { title: "Curses – The Crane Wives", cover: "", link: "" },
      { title: "Ship in a Bottle – fin", cover: "", link: "" },
      { title: "Driving Myself Home – Rose Betts", cover: "", link: "" },
      { title: "All I Ever Asked – Rachel Chinouriri", cover: "", link: "" },
      { title: "Never Love an Anchor – The Crane Wives", cover: "", link: "" },
      { title: "Swim With Sam – A Balladeer", cover: "", link: "" },
      { title: "Winter Flower – RM", cover: "", link: "" },
      { title: "uhgood – RM", cover: "", link: "" },
      { title: "Tokyo – RM", cover: "", link: "" }
    ],
    movies: [
      { title: "The Fault in Our Stars", genre: "Romance/Drama", link: "" },
      { title: "Bridge to Terabithia", genre: "Family/Drama/Fantasy", link: "" },
      { title: "My Girl", genre: "Drama/Romance", link: "" },
      { title: "Marley & Me", genre: "Comedy/Drama", link: "" },
      { title: "Atonement", genre: "Drama/Romance/War", link: "" },
      { title: "Hachi: A Dog’s Tale", genre: "Family/Drama", link: "" },
      { title: "The Green Mile", genre: "Crime/Drama/Fantasy", link: "" },
      { title: "The Pursuit of Happyness", genre: "Biography/Drama", link: "" },
      { title: "The Lion King", genre: "Animation/Drama/Adventure", link: "" },
      { title: "Grave of the Fireflies", genre: "Animation/War/Drama", link: "" },
      { title: "Million Dollar Baby", genre: "Drama/Sport", link: "" },
      { title: "The Lovely Bones", genre: "Drama/Fantasy", link: "" },
      { title: "Manchester by the Sea", genre: "Drama", link: "" },
      { title: "Eternal Sunshine of the Spotless Mind", genre: "Romance/Drama/Sci-Fi", link: "" },
      { title: "Schindler’s List", genre: "Biography/Drama/History", link: "" },
      { title: "The Notebook", genre: "Romance/Drama", link: "" },
      { title: "Requiem for a Dream", genre: "Drama", link: "" },
      { title: "Blue Valentine", genre: "Romance/Drama", link: "" },
      { title: "The Boy in the Striped Pajamas", genre: "War/Drama", link: "" },
      { title: "My Sister’s Keeper", genre: "Drama", link: "" }
    ]
  },
  VerySad: {
    quotes: [
      "It’s okay to rest when the world feels heavy.",
      "You are not alone, even when it feels that way.",
      "Let your pain be met with gentle care.",
      "There is strength in asking for help.",
      "One breath at a time is enough.",
      "Let your soul find shelter in kindness.",
      "You are worthy of love, especially now.",
      "The night may feel endless, but morning always comes.",
      "Let your sorrow be honored, not hidden.",
      "You are still here, and that is enough.",
      "Let hope be a quiet whisper in your heart.",
      "You are allowed to feel broken and still be whole.",
      "Let gentle thoughts hold you together.",
      "Your story isn’t over yet.",
      "Even small steps are steps forward.",
      "Let yourself be held by those who care.",
      "You are seen, you are valued.",
      "May you find peace, even in fragments.",
      "Let tomorrow bring a softer day."
    ],
    songs: [
      { title: "People, I've Been Sad – Christine and the Queens", cover: "", link: "" },
      { title: "idontwannabeyouanymore – Billie Eilish", cover: "", link: "" },
      { title: "Teen Idle – MARINA", cover: "", link: "" },
      { title: "Numb – Linkin Park", cover: "", link: "" },
      { title: "Creep – Radiohead", cover: "", link: "" },
      { title: "Sabry Aalil – Sherine", cover: "", link: "" },
      { title: "Trivia 轉: Seesaw – BTS", cover: "", link: "" },
      { title: "People – Agust D", cover: "", link: "" },
      { title: "Let Go – BTS", cover: "", link: "" },
      { title: "Reflection – BTS", cover: "", link: "" },
      { title: "Blue & Grey – BTS", cover: "", link: "" },
      { title: "Black Pearl – Sunmi", cover: "", link: "" },
      { title: "People Watching – Conan Gray", cover: "", link: "" },
      { title: "Lent – Autoheart", cover: "", link: "" },
      { title: "Linger – The Cranberries", cover: "", link: "" },
      { title: "Amygdala – Agust D", cover: "", link: "" },
      { title: "Seoul – RM", cover: "", link: "" },
      { title: "badbye – RM", cover: "", link: "" },
      { title: "Lonely – RM", cover: "", link: "" },
      { title: "Line Without a Hook", cover: "", link: "" }
    ],
    movies: [
      { title: "Requiem for a Dream", genre: "Drama", link: "" },
      { title: "Room", genre: "Drama/Thriller", link: "" },
      { title: "Manchester by the Sea", genre: "Drama", link: "" },
      { title: "Blue Valentine", genre: "Romance/Drama", link: "" },
      { title: "Atonement", genre: "Drama/Romance/War", link: "" },
      { title: "Precious", genre: "Drama", link: "" },
      { title: "The Fault in Our Stars", genre: "Romance/Drama", link: "" },
      { title: "The Boy in the Striped Pajamas", genre: "Drama/War", link: "" },
      { title: "The Road", genre: "Drama/Adventure", link: "" },
      { title: "Lion", genre: "Biography/Drama", link: "" },
      { title: "The Imitation Game", genre: "Biography/Drama/Thriller", link: "" },
      { title: "12 Years a Slave", genre: "Biography/Drama/History", link: "" },
      { title: "The Pianist", genre: "Biography/Drama/War", link: "" },
      { title: "Schindler’s List", genre: "Biography/Drama/History", link: "" },
      { title: "Dancer in the Dark", genre: "Drama/Musical/Crime", link: "" },
      { title: "Mystic River", genre: "Crime/Drama/Mystery", link: "" },
      { title: "The Lovely Bones", genre: "Drama/Fantasy", link: "" },
      { title: "Million Dollar Baby", genre: "Drama/Sport", link: "" },
      { title: "Hotel Rwanda", genre: "Biography/Drama/History", link: "" },
      { title: "Brokeback Mountain", genre: "Romance/Drama", link: "" }
    ]
  },
  Mad: {
    quotes: [
      "Let your anger fuel positive change.",
      "Breathe deep; you are bigger than your frustration.",
      "Channel your fire into something good.",
      "Let your voice be strong and kind.",
      "You have the power to choose your response.",
      "Anger is energy—transform it into action.",
      "Let calm be your comeback.",
      "You control the storm within.",
      "Pause, breathe, and rise above.",
      "You are more than this moment of anger.",
      "Let patience be your superpower.",
      "Speak your truth with compassion.",
      "Let your heart lead, not your temper.",
      "You can turn frustration into focus.",
      "Let your mind be the master of your mood.",
      "Even in anger, choose kindness.",
      "Let peace be your protest.",
      "You are resilient, even when challenged.",
      "Let go of what you can’t control."
    ],
    songs: [
      { title: "Motion Sickness – Phoebe Bridgers", cover: "", link: "" },
      { title: "Show and Tell – Melanie Martinez", cover: "", link: "" },
      { title: "Judas – Lady Gaga", cover: "", link: "" },
      { title: "Dis-ease – BTS", cover: "", link: "" },
      { title: "Paint the Town Red – Doja Cat", cover: "", link: "" },
      { title: "Boss Bitch – Doja Cat", cover: "", link: "" },
      { title: "Venus Flytrap – MARINA", cover: "", link: "" },
      { title: "I'm Not a Woman, I'm a God", cover: "", link: "" },
      { title: "Poker Face – Lady Gaga", cover: "", link: "" },
      { title: "Toxic – Britney Spears", cover: "", link: "" },
      { title: "Dangerous Woman – Ariana Grande", cover: "", link: "" },
      { title: "Lilith – Halsey and SUGA", cover: "", link: "" },
      { title: "Pied Piper – BTS", cover: "", link: "" },
      { title: "That's My Girl – Fifth Harmony", cover: "", link: "" },
      { title: "Circus – Britney Spears", cover: "", link: "" },
      { title: "Harpy Hare – Yaekolore", cover: "", link: "" },
      { title: "Huh?! – Agust D", cover: "", link: "" },
      { title: "Give It To Me – Agust D", cover: "", link: "" },
      { title: "Hectic – RM", cover: "", link: "" },
      { title: "Daechwita – Agust D", cover: "", link: "" }
    ],
    movies: [
      { title: "Mad Max: Fury Road", genre: "Action/Adventure/Sci-Fi", link: "" },
      { title: "John Wick", genre: "Action/Thriller", link: "" },
      { title: "Inception", genre: "Action/Sci-Fi/Thriller", link: "" },
      { title: "Django Unchained", genre: "Western/Drama", link: "" },
      { title: "The Dark Knight", genre: "Action/Crime/Drama", link: "" },
      { title: "The Revenant", genre: "Adventure/Drama/Thriller", link: "" },
      { title: "Sicario", genre: "Action/Crime/Drama", link: "" },
      { title: "Fight Club", genre: "Drama/Thriller", link: "" },
      { title: "The Bourne Ultimatum", genre: "Action/Thriller", link: "" },
      { title: "Prisoners", genre: "Crime/Drama/Thriller", link: "" },
      { title: "No Country for Old Men", genre: "Crime/Drama/Thriller", link: "" },
      { title: "The Equalizer", genre: "Action/Crime/Thriller", link: "" },
      { title: "Edge of Tomorrow", genre: "Action/Sci-Fi", link: "" },
      { title: "Looper", genre: "Action/Sci-Fi/Thriller", link: "" },
      { title: "Drive", genre: "Crime/Drama", link: "" },
      { title: "Deadpool", genre: "Action/Comedy", link: "" },
      { title: "Kingsman: The Secret Service", genre: "Action/Adventure/Comedy", link: "" },
      { title: "Guardians of the Galaxy", genre: "Action/Adventure/Comedy", link: "" },
      { title: "Logan", genre: "Action/Drama/Sci-Fi", link: "" },
      { title: "Black Panther", genre: "Action/Adventure/Sci-Fi", link: "" }
    ]
  }

};

export default recommendations;
